/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import conexao.MesasDAO;
import conexao.PedidosDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import negocio.Mesa;
import negocio.Pedido;

/**
 *
 * @author Dhiego
 */
public class CriaPedidoCliente extends javax.swing.JFrame {

    public CriaPedidoCliente(int mesa) throws SQLException {
        initComponents();

        //Mesa ms = new Mesa();
        //int mesa = ms.getIdmesa();
        
        lblIDMesa.setText(String.valueOf(mesa));//Atribui o valor da mesa selecionado na tela de login

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupoRdo1 = new javax.swing.ButtonGroup();
        txtIDmesa = new javax.swing.JTextField();
        lblIDMesa = new javax.swing.JLabel();
        asasdasda = new javax.swing.JLabel();
        pnlRolagem = new javax.swing.JScrollPane();
        pnlPedidos = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnOpcao1 = new javax.swing.JButton();
        btnOpcao2 = new javax.swing.JButton();
        btnOpcao3 = new javax.swing.JButton();
        shitakePNG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cria pedido cliente");

        lblIDMesa.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblIDMesa.setText("IDMESA");

        asasdasda.setText("(o id vai ser setado automaticamente de acordo com o login da mesa)");

        pnlRolagem.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        pnlRolagem.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnlPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("1 - Shitake fresco 72");

        jLabel3.setText("2 - Quatro queijos 55");

        jLabel4.setText("3 - Frango catupiry 40");

        btnOpcao1.setText("+");
        btnOpcao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcao1ActionPerformed(evt);
            }
        });

        btnOpcao2.setText("+");

        btnOpcao3.setText("+");

        shitakePNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/shitake.png"))); // NOI18N
        shitakePNG.setText("shitakeFot");

        javax.swing.GroupLayout pnlPedidosLayout = new javax.swing.GroupLayout(pnlPedidos);
        pnlPedidos.setLayout(pnlPedidosLayout);
        pnlPedidosLayout.setHorizontalGroup(
            pnlPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPedidosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOpcao1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(shitakePNG, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPedidosLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpcao3))
                    .addGroup(pnlPedidosLayout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addGap(119, 119, 119)
                        .addComponent(btnCancelar))
                    .addGroup(pnlPedidosLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOpcao2)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        pnlPedidosLayout.setVerticalGroup(
            pnlPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPedidosLayout.createSequentialGroup()
                .addGroup(pnlPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPedidosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pnlPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(btnOpcao1)))
                    .addGroup(pnlPedidosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(shitakePNG, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(pnlPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnOpcao3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(pnlPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnOpcao2))
                .addGap(36, 36, 36)
                .addGroup(pnlPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pnlRolagem.setViewportView(pnlPedidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblIDMesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtIDmesa, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(asasdasda))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlRolagem, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDmesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIDMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asasdasda)
                .addGap(70, 70, 70)
                .addComponent(pnlRolagem, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        setSize(new java.awt.Dimension(586, 473));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        dispose();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        Pedido ped = new Pedido();

        try {
            int idMesa;

            //validando campos
            if (txtIDmesa.getText().length() < 1) {
                JOptionPane.showMessageDialog(null, "Preencha o campo da mesa!");
                txtIDmesa.requestFocus();
            } else {

                idMesa = Integer.parseInt(txtIDmesa.getText());
                ped.setIdMesa(idMesa);

                PedidosDAO pz = new PedidosDAO();

                pz.criaPedido(ped);
                JOptionPane.showMessageDialog(null, "Pedido criado com sucesso!");

                limparTelaCadastro();
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        limparTelaCadastro();

    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnOpcao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcao1ActionPerformed

        //Insere a opcao1 no carrinho
        Pedido ped = new Pedido();
        int idMesa;

        idMesa = Integer.parseInt(txtIDmesa.getText());
        ped.setIdMesa(idMesa);

        PedidosDAO pz = new PedidosDAO();

        pz.criaPedido(ped);
        JOptionPane.showMessageDialog(null, "Pedido criado com sucesso!");

        limparTelaCadastro();

    }//GEN-LAST:event_btnOpcao1ActionPerformed
    public void limparTelaCadastro() {

        // Limpando campos Text
        txtIDmesa.setText("");

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asasdasda;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup btnGrupoRdo1;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnOpcao1;
    private javax.swing.JButton btnOpcao2;
    private javax.swing.JButton btnOpcao3;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel lblIDMesa;
    private javax.swing.JPanel pnlPedidos;
    private javax.swing.JScrollPane pnlRolagem;
    private javax.swing.JLabel shitakePNG;
    private javax.swing.JTextField txtIDmesa;
    // End of variables declaration//GEN-END:variables
}
