/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Inutil.ListagemPizzas;
import conexao.MesasDAO;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.Usuario;

/**
 *
 * @author Dhiego
 */
public class TelaAtendente extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaAtendente() {
        initComponents();
        //getContentPane().setBackground(Color.cyan); //deixa a tela principal com a cor azul
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        btnCriaPedido = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnMesas = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnCategoria = new javax.swing.JButton();
        btnPedidos1 = new javax.swing.JButton();
        Atendente = new javax.swing.JLabel();
        mnuBarTelaPrincipal = new javax.swing.JMenuBar();
        mnuCadastro = new javax.swing.JMenu();
        mnuCadastroDeProdutos = new javax.swing.JMenuItem();
        mnuListar = new javax.swing.JMenu();
        mnuListarPedidos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Digital Menu");

        btnCriaPedido.setText("Cria pedido cliente");
        btnCriaPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriaPedidoActionPerformed(evt);
            }
        });

        btnProdutos.setText("Produtos");
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });

        btnMesas.setText("Mesas");
        btnMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesasActionPerformed(evt);
            }
        });

        btnUsuarios.setText("Usuários");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnPedidos.setText("Pedidos");
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });

        btnCategoria.setText("Categoria");
        btnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaActionPerformed(evt);
            }
        });

        btnPedidos1.setText("Consulta pedido");
        btnPedidos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidos1ActionPerformed(evt);
            }
        });

        Atendente.setFont(new java.awt.Font("Harlow Solid Italic", 1, 24)); // NOI18N
        Atendente.setText("Atendente");

        mnuCadastro.setText("Cadastro");

        mnuCadastroDeProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        mnuCadastroDeProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pizza.png"))); // NOI18N
        mnuCadastroDeProdutos.setText("Cadastro de produtos");
        mnuCadastroDeProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroDeProdutosActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadastroDeProdutos);

        mnuBarTelaPrincipal.add(mnuCadastro);

        mnuListar.setText("Listar");

        mnuListarPedidos.setText("Consulta por Pedido");
        mnuListarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListarPedidosActionPerformed(evt);
            }
        });
        mnuListar.add(mnuListarPedidos);

        jMenuItem2.setText("Listas todos pedidos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuListar.add(jMenuItem2);

        mnuBarTelaPrincipal.add(mnuListar);

        setJMenuBar(mnuBarTelaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Atendente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(144, 144, 144))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPedidos1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCriaPedido)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Atendente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMesas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPedidos)
                    .addComponent(btnCriaPedido)
                    .addComponent(btnPedidos1))
                .addGap(79, 79, 79))
        );

        setSize(new java.awt.Dimension(414, 307));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadastroDeProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroDeProdutosActionPerformed

        try {
            new TelaProdutos().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaAtendente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_mnuCadastroDeProdutosActionPerformed

    private void mnuListarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListarPedidosActionPerformed

        new TelaConsultaPedido().setVisible(true);
    }//GEN-LAST:event_mnuListarPedidosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        new XTelaListaTodosPedidos().setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnCriaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriaPedidoActionPerformed
        MesasDAO mDAO = new MesasDAO();

        try {
            
            int mesa = Integer.parseInt(JOptionPane.showInputDialog(null, "Digite a mesa: ", "Digite a mesa", JOptionPane.INFORMATION_MESSAGE));
            
            if (mDAO.checkMesa(mesa)) {//verifica se a mesa existe

                JOptionPane.showMessageDialog(null, String.format("Bem-Vindo!: [Mesa: %d]",
                        mesa), "Bem-Vindo!", JOptionPane.INFORMATION_MESSAGE);

                new CriaPedidoCliente(mesa).setVisible(true);//Atribui o valor da mesa selecionado             

            } else {
                JOptionPane.showMessageDialog(null, "Mesa invalida! ", "Mesa não definida!", JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException ex) {
            Logger.getLogger(TelaAtendente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ae) {//exececao quando clica em cancelar, não está sendo tratada
            System.out.println("Entrada de dado da mesa cancelada. \n" + ae);

        }

    }//GEN-LAST:event_btnCriaPedidoActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        try {
            //abre tela produtos
            new TelaProdutos().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaAtendente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnProdutosActionPerformed

    private void btnMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesasActionPerformed

        new TelaMesa().setVisible(true);

    }//GEN-LAST:event_btnMesasActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed

        try {
            new TelaUsuarios().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaAtendente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed

        try {
            new TelaPedidos().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(TelaAtendente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed

        new TelaCategoria().setVisible(true);

    }//GEN-LAST:event_btnCategoriaActionPerformed

    private void btnPedidos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidos1ActionPerformed

        new TelaConsultaPedido().setVisible(true);

    }//GEN-LAST:event_btnPedidos1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Atendente;
    private javax.swing.JButton btnCategoria;
    private javax.swing.JButton btnCriaPedido;
    private javax.swing.JButton btnMesas;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnPedidos1;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar mnuBarTelaPrincipal;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenuItem mnuCadastroDeProdutos;
    private javax.swing.JMenu mnuListar;
    private javax.swing.JMenuItem mnuListarPedidos;
    // End of variables declaration//GEN-END:variables
}
