/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import conexao.AtendentesDAO;
import java.sql.SQLException;
import conexao.PedidosDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import negocio.Pedido;

/**
 *
 * @author Dhiego
 */
public class XTelaListaTodosPedidos extends javax.swing.JFrame {

    public XTelaListaTodosPedidos() {
        initComponents();

        DefaultTableModel modelo = (DefaultTableModel) tblListaPedidos.getModel();
        tblListaPedidos.setRowSorter(new TableRowSorter(modelo));
    }

    public void LerParaTabelaPorPedido() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) tblListaPedidos.getModel();
        model.setNumRows(0);
        
        PedidosDAO pizza = new PedidosDAO();

//Gera a lista de pizzas localmente, que sera preenchida
        List<Pedido> listaDePizzas;
        listaDePizzas = new ArrayList<>();

//pega (Obtem) a lista de pizzas atraves do atendente
        listaDePizzas = pizza.listaTodosOsPedidos();
        //for (Pedido pz : pDAO.buscaPorPedido(numPedido)) {
        for (Pedido pizzaLocal : listaDePizzas) {

            model.addRow(new Object[]{
            pizzaLocal.getIdPedido(),
            pizzaLocal.getStatus(),
            pizzaLocal.getPrecoTotal(),
            pizzaLocal.getIdMesa(),});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBotoes14 = new javax.swing.JPanel();
        lblListarTodosPedidos = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        pnlTabelaConsulta = new javax.swing.JScrollPane();
        tblListaPedidos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblListarTodosPedidos.setText("Listar todos os pedidos:");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoes14Layout = new javax.swing.GroupLayout(pnlBotoes14);
        pnlBotoes14.setLayout(pnlBotoes14Layout);
        pnlBotoes14Layout.setHorizontalGroup(
            pnlBotoes14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoes14Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlBotoes14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblListarTodosPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBotoes14Layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBotoes14Layout.setVerticalGroup(
            pnlBotoes14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoes14Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblListarTodosPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBotoes14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnLimpar))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        tblListaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Pedido", "Valor", "Mesa", "Atendente", "Pagamento"
            }
        ));
        pnlTabelaConsulta.setViewportView(tblListaPedidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlBotoes14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTabelaConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBotoes14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlTabelaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        setSize(new java.awt.Dimension(495, 355));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

        try {
            LerParaTabelaPorPedido();
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        ((DefaultTableModel) tblListaPedidos.getModel()).setRowCount(0);

    }//GEN-LAST:event_btnLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel lblListarTodosPedidos;
    private javax.swing.JPanel pnlBotoes14;
    private javax.swing.JScrollPane pnlTabelaConsulta;
    private javax.swing.JTable tblListaPedidos;
    // End of variables declaration//GEN-END:variables
}
